### ISSUE TITLE
[Bug] Making Jerky causes multiplayer server to crash

### ISSUE THREAD

**Issue by huntingtiger1004** [mrsterner/BrewinAndChewin-Fabric#13]
So I unfortunately lack a lot of information on this, as it is not personally my server, and the owner is currently at work. However, from what I've been able to test and from the portion of the of the log I was sent, apparently making jerky will cause our server to crash when it completes the process.

We're making it with minced beef from farmer's delight and putting it into the keg, and upon the timer completing it will crash the server, but upon loading up the ingredients will have not been spent (in spite of the jerky being created properly) and the keg will thus start another timer until the server crashes from it making jerky once again.

Here's what bit of logs I can give right now, I will try to get a full log from the owner once they're home.

```
[12:58:51] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.class_148: Ticking block entity
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:901) ~[server-intermediary.jar:?]
	at net.minecraft.class_3176.method_3813(class_3176.java:283) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[server-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1935.method_8389()" because "$$0" is null
	at net.minecraft.class_1799.<init>(class_1799.java:169) ~[server-intermediary.jar:?]
	at net.minecraft.class_1799.<init>(class_1799.java:152) ~[server-intermediary.jar:?]
	at dev.sterner.brewinandchewin.common.block.entity.KegBlockEntity.processFermenting(KegBlockEntity.java:386) ~[brewinandchewin-3.0.3+1.20.1.jar:?]
	at dev.sterner.brewinandchewin.common.block.entity.KegBlockEntity.fermentingTick(KegBlockEntity.java:157) ~[brewinandchewin-3.0.3+1.20.1.jar:?]
	at net.minecraft.class_2818$class_5563.method_31703(class_2818.java:662) ~[server-intermediary.jar:?]
	at net.minecraft.class_2818$class_5564.method_31703(class_2818.java:716) ~[server-intermediary.jar:?]
	at net.minecraft.class_1937.redirect$dgi000$observable$redirectTick(class_1937.java:9048) ~[server-intermediary.jar:?]
	at net.minecraft.class_1937.method_18471(class_1937.java:470) ~[server-intermediary.jar:?]
	at net.minecraft.class_3218.method_18765(class_3218.java:390) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897) ~[server-intermediary.jar:?]
	... 5 more
```

I apologize if I am misattributing the source of the error, I just wanted to report it here as I've repeatedly tested the bug under different conditions and arrived at the same result. We're running Fabric on Minecraft version 1.20.1 .

**Comment by nitrofenix** [comment]
Confirming the same happens with Kimchi on version `brewinandchewin-3.0.2+1.20.1` as part of AOF7 v2.1.2.

[crash-2024-05-26_18.37.29-server.txt](https://github.com/mrsterner/BrewinAndChewin-Fabric/files/15450748/crash-2024-05-26_18.37.29-server.txt)

**Comment by Sandshrew6** [comment]
Just had what I'm assuming is the same issue on singleplayer with pickles. Reloaded the world after the first crash and apparently the cucumbers weren't consumed, because when I got to it there were both pickles and the same amount of cucumbers I put in. 
[crash-2024-06-19_04.38.23-server.txt](https://github.com/user-attachments/files/15898027/crash-2024-06-19_04.38.23-server.txt)
[crash-2024-06-19_04.41.02-server.txt](https://github.com/user-attachments/files/15898028/crash-2024-06-19_04.41.02-server.txt)

**Comment by mrsterner** [comment]
fixed in 3.0.6

**Comment by SubordinalBlue** [comment]
Hmm... tested 3.0.6 on otherwise normal AoF7 2.3.0.
Does stop keg crashes... but also seems to stop the keg from processing a recipe at all.

Specifically tested first un-updated... keg's progress bar started right away when giving ingredients for kombucha... leading to crash, as expected.

Updated server and client to use 3.0.6, and start again.
No crash: 👍 
But, now doing the same thing—putting in ingredients for kombucha—and _nothing_ happens. No progress bar, nothing.

**Comment by SubordinalBlue** [comment]
Doh.
Update: missed that the kombucha recipe changed with the update (I think it did... didn't notice the green tea base the first time, and it did start processing with out it).

Now testing with the green tea in there too... and seems to be working.

Apologies for the erroneous previous post. Unless something unexpected happens when the recipe completes, I'll just stay quiet, lol.
