### ISSUE TITLE
Keg ticking block / Crash the client sometimes

### ISSUE THREAD

**Issue by UnnamedWei** [mrsterner/BrewinAndChewin-Fabric#14]
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1935.method_8389()" because "$$0" is null
    at net.minecraft.class_1799.<init>(class_1799.java:169)
    at net.minecraft.class_1799.<init>(class_1799.java:152)
    at dev.sterner.brewinandchewin.common.block.entity.KegBlockEntity.processFermenting(KegBlockEntity.java:386)
    at dev.sterner.brewinandchewin.common.block.entity.KegBlockEntity.fermentingTick(KegBlockEntity.java:157)
    at net.minecraft.class_2818$class_5563.mixinextras$bridge$tick$11(class_2818.java)
    at com.bawnorton.neruina.handler.TickHandler.safelyTickBlockEntity(TickHandler.java:169)
    at net.minecraft.class_2818$class_5563.wrapOperation$egf000$neruina$catchTickingBlockEntity$notTheCauseOfTickLag(class_2818.java:1287)
    at net.minecraft.class_2818$class_5563.method_31703(class_2818.java:662)
    at net.minecraft.class_2818$class_5564.method_31703(class_2818.java:716)
    at net.minecraft.class_1937.method_18471(class_1937.java:470)
    at net.minecraft.class_3218.method_18765(class_3218.java:390)
    at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897)
    at net.minecraft.class_3176.method_3813(class_3176.java:283)
    at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824)
    at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671)
    at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
    at java.base/java.lang.Thread.run(Thread.java:1623)

**Comment by YOUNIN15** [comment]
> java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1935.method_8389()" because "$$0" is null at net.minecraft.class_1799.(class_1799.java:169) at net.minecraft.class_1799.(class_1799.java:152) at dev.sterner.brewinandchewin.common.block.entity.KegBlockEntity.processFermenting(KegBlockEntity.java:386) at dev.sterner.brewinandchewin.common.block.entity.KegBlockEntity.fermentingTick(KegBlockEntity.java:157) at net.minecraft.class_2818$class_5563.mixinextras$bridge$tick$11(class_2818.java) at com.bawnorton.neruina.handler.TickHandler.safelyTickBlockEntity(TickHandler.java:169) at net.minecraft.class_2818$class_5563.wrapOperation$egf000$neruina$catchTickingBlockEntity$notTheCauseOfTickLag(class_2818.java:1287) at net.minecraft.class_2818$class_5563.method_31703(class_2818.java:662) at net.minecraft.class_2818$class_5564.method_31703(class_2818.java:716) at net.minecraft.class_1937.method_18471(class_1937.java:470) at net.minecraft.class_3218.method_18765(class_3218.java:390) at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897) at net.minecraft.class_3176.method_3813(class_3176.java:283) at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824) at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671) at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) at java.base/java.lang.Thread.run(Thread.java:1623)

Did you solve it? In my world a tower with some barrels was loaded and until after deleting the mod you can't go to that tower because it crashes the game.
